import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  ru: {
    appName: 'BarinBil',
    appSlogan: 'Умная IT-платформа и комьюнити',
    roleStudent: 'Участник',
    roleOrganizer: 'Организатор',
    levelBeginner: 'Новичок',
    levelAmateur: 'Любитель',
    levelPro: 'Профи',
    levelMaster: 'Мастер',
    allEvents: 'Все события',
    createEvent: 'Создать',
    searchPlaceholder: 'Поиск хакатонов, митапов, воркшопов...',
    filterAll: 'Все',
    filterHackathon: '🏆 Хакатоны',
    filterMeetup: '🎤 Митапы',
    filterWorkshop: '💻 Воркшопы',
    filterAI: '🤖 AI & Data',
    filterWeb3: '⛓️ Web3',
    filterDesign: '🎨 Дизайн',
    filterBeginnerOnly: 'Только для новичков',
    cityAll: 'Все локации',
    cityAlmaty: 'Алматы',
    cityAstana: 'Астана',
    cityOnline: 'Онлайн',
    sortPopular: 'Популярные',
    sortNewest: 'Свежие',
    sortSoon: 'Ближайшие',
    sortXP: 'Больше XP',
    registered: 'Вы записаны',
    registerBtn: 'Участвовать (+50 XP)',
    registeredCount: 'участников',
    prizePool: 'Призовой фонд',
    aiMentorBtn: '✨ AI-Советник',
    aiMentorLoading: 'AI анализирует программу...',
    agenda: 'Программа мероприятия',
    speakers: 'Спикеры и менторы',
    addToCalendar: 'В календарь',
    shareTelegram: 'Поделиться',
    saveBookmark: 'В закладки',
    bookmarked: 'Сохранено',
    navFeed: 'Лента',
    navTeams: 'Команды',
    navQuests: 'Квесты',
    navAI: 'AI Коуч',
    navProfile: 'Профиль',
    questsTitle: 'Ежедневные квесты и ачивки',
    dailyStreak: 'Дней стрик',
    claimXP: 'Забрать',
    claimed: 'Получено',
    leaderboardTitle: 'Таблица лидеров',
    topStudents: 'Топ разработчиков',
    teamFinderTitle: 'Поиск команды на хакатон',
    createTeamPost: '+ Создать анкету',
    lookForTeammates: 'Ищут тиммейтов',
    contactInTg: 'Написать в TG',
    neededRoles: 'Нужны в команду',
    profileTitle: 'Профиль разработчика',
    myRegistrations: 'Мои билеты & ивенты',
    achievementsTitle: 'Достижения и бейджи',
    skillMatrix: 'Матрица навыков',
    logout: 'Выйти из аккаунта',
    onboardingTitle: 'Добро пожаловать в BarinBil',
    onboardingSub: 'Персональная платформа для роста в IT',
    stepRole: 'Кто ты?',
    stepDirection: 'Твоё направление',
    stepLevel: 'Твой текущий уровень',
    continue: 'Продолжить',
    back: 'Назад',
    saving: 'Сохраняем...',
    soundOn: 'Звук включен',
    soundOff: 'Звук выключен',
    themeDark: 'Тёмная тема',
    themeLight: 'Светлая тема',
    themeCyber: 'Кибер тема',
    aiCoachTitle: 'AI-Коуч и Карьерный Наставник',
    aiCoachPromptPlaceholder: 'Спроси совет о карьере, технологиях или хакатоне...',
    askAICoach: 'Спросить AI',
    generateRoadmap: '🚀 Сгенерировать Roadmap подготовки',
    roadmapTitle: 'Персональный план подготовки',
  },
  kz: {
    appName: 'BarinBil',
    appSlogan: 'Ақылды IT-платформа және комьюнити',
    roleStudent: 'Қатысушы',
    roleOrganizer: 'Ұйымдастырушы',
    levelBeginner: 'Жаңадан бастаушы',
    levelAmateur: 'Әуесқой',
    levelPro: 'Маман (Профи)',
    levelMaster: 'Шебер',
    allEvents: 'Барлық іс-шаралар',
    createEvent: 'Құру',
    searchPlaceholder: 'Хакатондар, митаптар, воркшоптар іздеу...',
    filterAll: 'Барлығы',
    filterHackathon: '🏆 Хакатондар',
    filterMeetup: '🎤 Митаптар',
    filterWorkshop: '💻 Воркшоптар',
    filterAI: '🤖 AI & Data',
    filterWeb3: '⛓️ Web3',
    filterDesign: '🎨 Дизайн',
    filterBeginnerOnly: 'Тек бастаушылар үшін',
    cityAll: 'Барлық қалалар',
    cityAlmaty: 'Алматы',
    cityAstana: 'Астана',
    cityOnline: 'Онлайн',
    sortPopular: 'Танымал',
    sortNewest: 'Жаңа',
    sortSoon: 'Жақында',
    sortXP: 'Көп XP',
    registered: 'Тіркелдіңіз',
    registerBtn: 'Қатысу (+50 XP)',
    registeredCount: 'қатысушы',
    prizePool: 'Жүлде қоры',
    aiMentorBtn: '✨ AI-Кеңесші',
    aiMentorLoading: 'AI бағдарламаны талдауда...',
    agenda: 'Іс-шара бағдарламасы',
    speakers: 'Спикерлер мен менторлар',
    addToCalendar: 'Күнтізбеге',
    shareTelegram: 'Бөлісу',
    saveBookmark: 'Сақтау',
    bookmarked: 'Сақталды',
    navFeed: 'Таспа',
    navTeams: 'Командалар',
    navQuests: 'Квесттер',
    navAI: 'AI Коуч',
    navProfile: 'Профиль',
    questsTitle: 'Күнделікті квесттер мен жетістіктер',
    dailyStreak: 'Күндік стрик',
    claimXP: 'Алу',
    claimed: 'Алынды',
    leaderboardTitle: 'Көшбасшылар кестесі',
    topStudents: 'Үздік әзірлеушілер',
    teamFinderTitle: 'Хакатонға команда іздеу',
    createTeamPost: '+ Сауалнама қосу',
    lookForTeammates: 'Команда іздеушілер',
    contactInTg: 'TG арқылы жазу',
    neededRoles: 'Командаға қажет',
    profileTitle: 'Әзірлеуші профилі',
    myRegistrations: 'Менің билеттерім мен шараларым',
    achievementsTitle: 'Жетістіктер мен бейдждер',
    skillMatrix: 'Дағдылар матрицасы',
    logout: 'Шығу',
    onboardingTitle: 'BarinBil-ге қош келдіңіз',
    onboardingSub: 'IT саласында дамудың жеке платформасы',
    stepRole: 'Сіз кімсіз?',
    stepDirection: 'Сіздің бағытыңыз',
    stepLevel: 'Қазіргі деңгейіңіз',
    continue: 'Жалғастыру',
    back: 'Артқа',
    saving: 'Сақталуда...',
    soundOn: 'Дыбыс қосулы',
    soundOff: 'Дыбыс өшірулі',
    themeDark: 'Қараңғы стиль',
    themeLight: 'Жарық стиль',
    themeCyber: 'Кибер стиль',
    aiCoachTitle: 'AI-Коуч және мансап менторы',
    aiCoachPromptPlaceholder: 'Мансап, технология немесе хакатон туралы сұраңыз...',
    askAICoach: 'AI-дан сұрау',
    generateRoadmap: '🚀 Дайындық Roadmap-ын жасау',
    roadmapTitle: 'Жеке дайындық жоспары',
  },
  en: {
    appName: 'BarinBil',
    appSlogan: 'Smart Tech Events & Gamified Community',
    roleStudent: 'Participant',
    roleOrganizer: 'Organizer',
    levelBeginner: 'Beginner',
    levelAmateur: 'Amateur',
    levelPro: 'Pro',
    levelMaster: 'Master',
    allEvents: 'All Events',
    createEvent: 'Create',
    searchPlaceholder: 'Search hackathons, meetups, workshops...',
    filterAll: 'All',
    filterHackathon: '🏆 Hackathons',
    filterMeetup: '🎤 Meetups',
    filterWorkshop: '💻 Workshops',
    filterAI: '🤖 AI & Data',
    filterWeb3: '⛓️ Web3',
    filterDesign: '🎨 Design',
    filterBeginnerOnly: 'Beginner Friendly Only',
    cityAll: 'All Locations',
    cityAlmaty: 'Almaty',
    cityAstana: 'Astana',
    cityOnline: 'Online',
    sortPopular: 'Popular',
    sortNewest: 'Newest',
    sortSoon: 'Soonest',
    sortXP: 'Highest XP',
    registered: 'Registered',
    registerBtn: 'Join (+50 XP)',
    registeredCount: 'attendees',
    prizePool: 'Prize Pool',
    aiMentorBtn: '✨ AI Mentor',
    aiMentorLoading: 'AI is analyzing event...',
    agenda: 'Event Agenda',
    speakers: 'Speakers & Mentors',
    addToCalendar: 'To Calendar',
    shareTelegram: 'Share',
    saveBookmark: 'Bookmark',
    bookmarked: 'Bookmarked',
    navFeed: 'Feed',
    navTeams: 'Teams',
    navQuests: 'Quests',
    navAI: 'AI Coach',
    navProfile: 'Profile',
    questsTitle: 'Daily Quests & Achievements',
    dailyStreak: 'Day Streak',
    claimXP: 'Claim',
    claimed: 'Claimed',
    leaderboardTitle: 'Leaderboard',
    topStudents: 'Top Developers',
    teamFinderTitle: 'Hackathon Team Finder',
    createTeamPost: '+ Post Request',
    lookForTeammates: 'Looking for Teammates',
    contactInTg: 'Chat on TG',
    neededRoles: 'Needed in Team',
    profileTitle: 'Developer Profile',
    myRegistrations: 'My Tickets & Events',
    achievementsTitle: 'Achievements & Badges',
    skillMatrix: 'Skill Matrix',
    logout: 'Log Out',
    onboardingTitle: 'Welcome to BarinBil',
    onboardingSub: 'Your personal springboard in tech',
    stepRole: 'Who are you?',
    stepDirection: 'Your Direction',
    stepLevel: 'Your Current Level',
    continue: 'Continue',
    back: 'Back',
    saving: 'Saving...',
    soundOn: 'Sound On',
    soundOff: 'Sound Off',
    themeDark: 'Dark Theme',
    themeLight: 'Light Theme',
    themeCyber: 'Cyber Theme',
    aiCoachTitle: 'AI Coach & Career Mentor',
    aiCoachPromptPlaceholder: 'Ask advice about career, tech stacks, or hackathons...',
    askAICoach: 'Ask AI',
    generateRoadmap: '🚀 Generate Hackathon Roadmap',
    roadmapTitle: 'Personal Prep Plan',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('barinbil_lang') || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('barinbil_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['ru']?.[key] || key;
  };

  const switchLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
